import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <html lang="en">
      <head>
      <script
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4778813145666839"
        crossorigin="anonymous"
      />
      </head>
      <body className="bg-white h-screen w-screen">
      <NavBar></NavBar>
      <div className={inter.className}>{children}</div>
      </body>
    </html>
    </>
  );
}
